on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Lint Code
        run: flutter analyze

      - name: Ensure App Builds
        run: flutter build apk --release

      - name: Upload Release to GitHub
        uses: ncipollo/release-action@v1
        with:
          name: "Release v1.0.${{ github.run_number }}"
          artifacts: "build/app/outputs/flutter-apk/release/*.apk"
          tag: "release"
          token: ${{ secrets.GITHUB_TOKEN }}