on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/keystore.jks

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Signed APK
        run: |
          ./gradlew assembleRelease

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.yourapp.package  # Change to your app's package name
          releaseFiles: app/build/outputs/apk/release/app-release.apk
          track: production  # Options: internal, alpha, beta, production
          status: completed
